
Program("coin_change.cpp", CCFLAGS=[ '/EHsc'])
Program("sherlock.cpp", CCFLAGS=[ '/EHsc'])
Program("decibinary.cpp", CCFLAGS=[ '/EHsc'])
Program("candies.cpp", CCFLAGS=[ '/EHsc'])
Program("kingdom.cpp", CCFLAGS=[ '/EHsc'])
Program("max_subarray.cpp", CCFLAGS=[ '/EHsc'])
Program("abbr.cpp", CCFLAGS=[ '/EHsc'])
Program("stock_max.cpp", CCFLAGS=[ '/EHsc'])
Program("candles.cpp", CCFLAGS=[ '/EHsc'])

