
Program("twin_array.cpp", CCFLAGS=[ '/EHsc'])
Program("palindrome.cpp", CCFLAGS=[ '/EHsc'])
Program("pal_subseq.cpp", CCFLAGS=[ '/EHsc'])
Program("disjoint_set.cpp", CCFLAGS=[ '/EHsc'])
Program("pal_table.cpp", CCFLAGS=[ '/EHsc'])
Program("graph.cpp", CCFLAGS=[ '/EHsc'])
Program("bonnie_graph.cpp", CCFLAGS=[ '/EHsc'])

